### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by baimafeima** [jfveronelli/sqink#1]
Could you add releases (versioned tarballs, flatpak, AppImage) here on GitHub?

**Comment by jfveronelli** [comment]
Only the latest release will be added as a zip file.

**Comment by baimafeima** [comment]
Does your application work under Linux-based operating systems? If yes, a versioned tarball release is necessary in order to add it to the repositories of my operating system of choice.

**Comment by jfveronelli** [comment]
Yes, it works under Linux. A versioned tarball has been added.

**Comment by baimafeima** [comment]
@jfveronelli Could you tag the releases because then they are automatically visible here on GitHub under the release section. This would also allow for the changelog to be visible.

**Comment by jfveronelli** [comment]
Done, thanks for the suggestion.
